---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue-deployment
  labels:
    type: proxy
    author: abhi
spec:
  replicas: 3
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: nginx-deployment-pod
      labels:
        type: proxy
        author: abhi
    spec:
      containers:
        - name: mynginx
          image: nginx:1.24
          ports:
            - containerPort: 80
              hostPort: 9999
...

