---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    type: db
    author: abhi
spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: abhi
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: myuser


