---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    type: ci-cd
    author: abhi
spec:
  containers:
    - name: myjenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 8080
