---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  namespace: test-ns
  labels:
    type: CMS
    author: abhi
spec:
  containers:
    - name: mywordpress
      image: wordpress
      ports:
        - containerPort: 80
          hostPort: 8080
...
