---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    author: abhi
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
    type: ci-cd
    author: abhi

...
