---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-app-deployment
  labels:
    name: postgres-app
    author: abhi
spec:
  selector:
    matchLabels:
      name: postgres-app
  template:
    metadata:
      name: postgres-app-pod
      labels:
        name: postgres-app
    spec:
      containers:
        - name: postgers-app
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: abhi
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_DB
              value: mydb
          ports:
            - 7070:5432

...
