---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    author: abhi
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePOrt: 30008
  selector:
    name: voting-app

